### ISSUE TITLE
Changing the order of the dimensions leads to a stack trace

### ISSUE THREAD

**Issue by sukhwinder33445** [Icinga/icingaweb2-module-cube#69]
## Describe the bug

If you click on the up or down arrow to change the order of the dimension, the stack trace error occurs.

## To Reproduce
1. Add two or more dimensions
2. Change the order of dimensions
## Screenshots
![Screenshot 2021-07-05 at 11 24 41](https://user-images.githubusercontent.com/54990055/124450438-b494bc00-dd84-11eb-9cd2-58a2a967142e.png)

![Screenshot 2021-07-05 at 11 24 58](https://user-images.githubusercontent.com/54990055/124450482-bfe7e780-dd84-11eb-8c99-033c921bd45d.png)

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.8.2
* PHP version used (`php --version`): PHP 8.0.7

**Comment by nilmerg** [comment]
Fixed since #68. Please pull the latest changes.

**Comment by sukhwinder33445** [comment]
I already have the lastest changes. It seems that you forgot to change the `moveDimensionDown()` method. 😉

**Comment by nilmerg** [comment]
Thanks -.-
